services:
    express:
        container_name: drm-mina-express
        restart: unless-stopped
        build:
            context: ./
            dockerfile: ./docker/express/Dockerfile
        ports:
            - "3333:3333"
        depends_on:
            - sequencer-1
            - sequencer-2
            - sequencer-3
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        networks:
            - app-network

    sequencer-1:
        container_name: drm-mina-sequencer-1
        restart: unless-stopped
        build:
            context: ./
            dockerfile: ./docker/sequencer/Dockerfile
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - GAME_TOKEN_ADDRESS=B62qqhNYa8zdCnNMZqtPcgrUV72342LPF58sM5tHVRsnLtowNMjwxnW
            - DRM_ADDRESS=B62qrCgG8CcQJiTDj2DoaWTpUCo6Tm6VECFRdSoXVD2TbctHL5jjgbX
        networks:
            - app-network

    sequencer-2:
        container_name: drm-mina-sequencer-2
        restart: unless-stopped
        build:
            context: ./
            dockerfile: ./docker/sequencer/Dockerfile
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - GAME_TOKEN_ADDRESS=B62qoPeVuNurBLbrdEvyjLbTE7odRq3fKE2ZpUfALn1xnXtt5cQxZgV
            - DRM_ADDRESS=B62qnijB6HtyDRHcYM3pZ1ZAUd2kFpT33acbUpCcRGygHVtVCADGiiG
        networks:
            - app-network

    sequencer-3:
        container_name: drm-mina-sequencer-3
        restart: unless-stopped
        build:
            context: ./
            dockerfile: ./docker/sequencer/Dockerfile
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - GAME_TOKEN_ADDRESS=B62qnddkpwSvKLNcpUUchdW1AemQ72DTNaxyiUE9TKqEJcoQpM2fDrM
            - DRM_ADDRESS=B62qjDofX5d8Z8Lp7HKZjT7yDgRXH2aDMK76n2orUSFJat6umgZyUMS
        networks:
            - app-network

    settlement:
        container_name: drm-mina-settlement
        restart: unless-stopped
        build:
            context: ./
            dockerfile: ./docker/settlement/Dockerfile
        environment:
            - DRM_ADDR1=B62qkBz8sKUr48HbnUeVt9WvpUJ6tyK4YmuUsAxTMdQ7Lo9bX8iw364
            - DRM_ADDR2=B62qjubSRcRR2FHN1AMuTy2nAvmAUfof6L6EovgixmoE7DykvZYzz6B
            - DRM_ADDR3=B62qmSFqFLF8wbpGQYriJn13AwDDsCqPrSkbAJz5ZAHknAzDGgRFyMG

    redis:
        image: "redis:7.2.6-alpine"
        container_name: drm-mina-redis
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
        # ports:
        #     - "6379:6379"
        volumes:
            # - redis-data:/data
            - ./data/redis:/data
            - ./redis.conf:/redis.conf
        command: ["redis-server", "/redis.conf"]
        networks:
            - app-network

# volumes:
#     redis-data:

networks:
    app-network:
        driver: bridge
