version: "3.8"

services:
    express:
        build:
            context: ./
            dockerfile: ./docker/express/Dockerfile
        ports:
            - "3333:3333"
        depends_on:
            - sequencer
        networks:
            - app-network

    sequencer:
        build:
            context: ./
            dockerfile: ./docker/sequencer/Dockerfile
        ports:
            - "3334:3334"
        networks:
            - app-network

    # settlement:
    #     build:
    #         context: ./
    #         dockerfile: ./docker/settlement/Dockerfile
    #     networks:
    #         - app-network

networks:
    app-network:
        driver: bridge
